name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Portfolio
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Upload everything in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
